#!/bin/bash

#STOP ALL SERVERS
pkill -f 'server.js'

#RUN THE SERVERS
nodemon ./emphora.local/server.js > /tmp/emphora.log>&1 &
nodemon ./twitter.local/server.js > /tmp/twitter.log>&1 &
nodemon ./dropbox.local/server.js > /tmp/dropbox.log>&1 &

#START SASS COMPILER
/usr/local/bin/node-sass --watch ./ --output ./ --sourcemap true  > /tmp/sass.log>&1 &
