########################################################
# HTTP fallback (optional for local dev)
########################################################
<VirtualHost *:80>
    ServerName www.melify.com
    ServerAlias melify.local
    Redirect permanent "/" "https://www.melify.com/"
</VirtualHost>

<VirtualHost *:80>
    ServerName dropbox.melify.com
    ServerAlias dropbox.local
    Redirect permanent "/" "https://dropbox.melify.com/"
</VirtualHost>

<VirtualHost *:80>
    ServerName wc.melify.com
    ServerAlias wc.local
    Redirect permanent "/" "https://wc.melify.com/"
</VirtualHost>

<VirtualHost *:80>
    ServerName bookmarker.melify.com
    ServerAlias bookmarker.local
    Redirect permanent "/" "https://bookmarker.melify.com/"
</VirtualHost>

<VirtualHost *:80>
    ServerName emphora.melify.com
    ServerAlias emphora.local
    Redirect permanent "/" "https://emphora.melify.com/"
</VirtualHost>

<VirtualHost *:80>
    ServerName twitter.melify.com
    ServerAlias twitter.local
    Redirect permanent "/" "https://twitter.melify.com/"
</VirtualHost>
